# Generated by Django 6.0.6 on 2026-06-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alat', models.CharField(max_length=50, unique=True)),
                ('nama_kolam', models.CharField(blank=True, max_length=100)),
                ('status_aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Daftar Alat',
            },
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_daerah', models.CharField(max_length=100, unique=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Daftar Lokasi',
            },
        ),
        migrations.CreateModel(
            name='DataSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('do_level', models.FloatField(verbose_name='Dissolved Oxygen (mg/L)')),
                ('tds_level', models.FloatField(verbose_name='Total Dissolved Solids (ppm)')),
                ('jsn_distance', models.FloatField(verbose_name='Ketinggian Air JSN (cm)')),
                ('suhu_air', models.FloatField(verbose_name='Suhu Air (°C)')),
                ('suhu_lingkungan', models.FloatField(verbose_name='Suhu Lingkungan (°C)')),
                ('alat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sensor', to='dashboard.alat')),
            ],
            options={
                'verbose_name_plural': 'Data Sensor',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='alat',
            name='lokasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_alat', to='dashboard.lokasi'),
        ),
    ]
