# Generated by Django 6.0.6 on 2026-06-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasensor',
            name='device_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
