# Generated by Django 6.0.6 on 2026-06-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_datasensor_device_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasensor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
