# Generated by Django 6.1 on 2026-08-08 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_datasensor_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay1', models.BooleanField(default=False, verbose_name='Relay 1 (D25 - Pompa 1)')),
                ('relay2', models.BooleanField(default=False, verbose_name='Relay 2 (D16 - Pompa 2)')),
                ('relay3', models.BooleanField(default=False, verbose_name='Relay 3 (D17 - Heater)')),
                ('relay4', models.BooleanField(default=False, verbose_name='Relay 4 (D13 - Feeder)')),
                ('relay5', models.BooleanField(default=False, verbose_name='Relay 5 (D14 - Solenoid Valve)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relay_state', to='dashboard.alat')),
            ],
            options={
                'verbose_name_plural': 'Status Relay',
            },
        ),
    ]
