# Generated by Django 6.0.6 on 2026-08-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_relaystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasensor',
            name='kelembaban_udara',
            field=models.FloatField(default=0.0, verbose_name='Kelembaban Udara (%)'),
        ),
    ]
