# Generated by Django 6.1.1 on 2026-09-26 12:11

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_datasensor_kelembaban_udara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Target device, harus match Alat.id_alat (mis: ESP32-001)', max_length=50)),
                ('version', models.CharField(help_text='Versi firmware, mis: v1.2.0', max_length=32)),
                ('file', models.FileField(help_text='File .bin hasil build ESP-IDF', upload_to=dashboard.models.Firmware.firmware_upload_path)),
                ('notes', models.TextField(blank=True, help_text='Catatan rilis (opsional)', null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle - Siap dikirim'), ('queued', 'Dikirim ke ESP32...'), ('started', 'ESP32 Memulai OTA'), ('downloading', 'Mengunduh Firmware'), ('verifying', 'Verifikasi Firmware'), ('success', 'Berhasil! Menunggu Reboot'), ('error', 'Gagal')], default='idle', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=128, null=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Firmware OTA',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
